INSERT INTO regiones (id, nombre) VALUES(1, 'Sudamerica');
INSERT INTO regiones (id, nombre) VALUES(2, 'Centroamerica');
INSERT INTO regiones (id, nombre) VALUES(3, 'Norteamerica');
INSERT INTO regiones (id, nombre) VALUES(4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES(5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES(6, 'Africa');
INSERT INTO regiones (id, nombre) VALUES(7, 'Oceania');
INSERT INTO regiones (id, nombre) VALUES(8, 'Antartida');

INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(1, 'Andres', 'Guszman', 'andres@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(2, 'Leo', 'Perez', 'leo@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(4, 'Liz', 'Guszman', 'liz@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(4, 'Luz', 'Gutierrez', 'luz@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(4, 'Jonas', 'Joe', 'jonas@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(3, 'Joel', 'Yni', 'joel@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(3, 'Julio', 'GUz', 'julio@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(3, 'Omar', 'Omar', 'omar@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(5, 'Jesus', 'Guszman', 'jesus@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(6, 'Josue', 'Guszman', 'josue@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(7, 'Darling', 'Guszman', 'darlin@gmail.com', '2021-01-01');
INSERT INTO clientes (region_id, nombre, apellido, email, created_at) VALUES(8, 'Talia', 'Perez', 'talia@gmail.com', '2021-01-01');